version: '3'

services:
  php:
    container_name: ${PROJECT}_php
    image: ${PROJECT}_php:${TAG}
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    depends_on:
      - db
    volumes:
      - './laravel:/site'

  server:
    container_name: ${PROJECT}_nginx
    image: ${PROJECT}_nginx:${TAG}
    build:
      context: .
      dockerfile: docker/nginx/Dockerfile
    ports:
      - 80:80
    depends_on:
      - php
    volumes:
      - './laravel:/site'

  db:
    image: mysql:8
    container_name: ${PROJECT}_mysql
    restart: unless-stopped
    hostname: ${DB_HOST}
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - 'mysql-data:/var/lib/mysql'

volumes:
  mysql-data:

networks:
  default:
    driver: bridge
    name: internet
