version: '3'

services:
  php:
    container_name: 'php'
    image: ${APP_ENV}php:${TAG}
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    volumes:
      - './:/site'

  server:
    container_name: 'nginx'
    image: ${APP_ENV}nginx:${TAG}
    build:
      context: .
      dockerfile: docker/nginx/Dockerfile
    ports:
      - 80:80
    volumes:
      - './:/site'

  db:
    container_name: 'mysql'
    image: ${APP_ENV}mysql:${TAG}
    build:
      context: ./
      dockerfile: docker/mysql/Dockerfile
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASSWORD}
    volumes:
      - './docker/volumes/mysql:/var/lib/mysql'

networks:
  default:
    driver: bridge
    name: internet
